spring.application.name=crud_operation

server.port=${PORT:8080}

# context path (optional)
server.servlet.context-path=${SERVER_PATH:/}

# frontend url
frontend.url=${FRONTEND_URL}

#JWT SECRET KEY 
jwt.secret.key=${JWT_SECRET_KEY}

# datasource
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#very risky only for learning
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=false

springdoc.swagger-ui.path=${SWAGGER_URL:/swagger}


#University logo
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


# --------otp----
# Gmail's server for sending mail
spring.mail.host=smtp.gmail.com
# TLS port used for secure mail
spring.mail.port=587
# Gmail login
spring.mail.username=${EMAIL_FOR_OTP}

# app password
spring.mail.password=${PASSWORD_FOR_OTP}

# Tells gamil we are logging in with creadentials
spring.mail.properties.mail.smtp.auth=true
# Enable encryption for security
spring.mail.properties.mail.smtp.starttls.enable=true

